import Navbar from '@/components/Navbar/navbar';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className='relative w-full mx-auto mt-[62px] px-32 py-12 box-border'>
          {props.children}
        </div>
      </body>
    </html>
  )
}
